name = "{{name}}"
host = "{{host}}"
port = {{port}}
players = {{players}}
password = "{{password}}"
announce = {{announce}}
token = "{{token}}"
language = "{{language}}"
debug = {{debug}}
streamingDistance = {{streamingDistance}}
migrationDistance = {{migrationDistance}}
timeout = {{timeout}}
announceRetryErrorDelay = {{announceRetryErrorDelay}}
announceRetryErrorAttempts = {{announceRetryErrorAttempts}}
duplicatePlayers = {{duplicatePlayers}}
{{UserSettings}}