# This file is controlled by AMP
# Configure additional settings via the AMP UI

[Head]
"Current Version" = ""
"Latest Version" = ""

[Main]
[Main.General]
Account = {{Account}}
Server = {{Server}}
AccountType = "{{AccountType}}"
Method = "{{Method}}"
AuthUser = ""

[Main.General.AuthServer]
Port = 443
AuthlibInjectorAPIPath = "/api/yggdrasil"
UseHttps = true
Host = ""

[Main.Advanced]
Language = "en_us"
LoadMccTranslation = true
ConsoleTitle = "%username%@%serverip% - Minecraft Console Client"
InternalCmdChar = "slash"
MessageCooldown = 1.0
MaxChatMessageLength = 0
BotOwners = [ "player1", "player2" ]
MinecraftVersion = "{{MinecraftVersion}}"
EnableForge = "no"
BrandInfo = "mcc"
ChatbotLogFile = ""
PrivateMsgsCmdName = "tell"
ShowSystemMessages = true
ShowXPBarMessages = true
ShowChatLinks = true
ShowInventoryLayout = true
ShowEffectNamesInTUI = false
ShowGithubStarReminder = true
TerrainAndMovements = false
MoveHeadWhileWalking = true
MovementSpeed = 2
TemporaryFixBadpacket = false
InventoryHandling = false
EntityHandling = false
SessionCache = "disk"
ProfileKeyCache = "disk"
ResolveSrvRecords = "fast"
PlayerHeadAsIcon = true
ExitOnFailure = false
CacheScript = true
Timestamps = false
AutoRespawn = false
MinecraftRealms = false
TcpTimeout = 30
EnableEmoji = true
MinTerminalWidth = 16
MinTerminalHeight = 10
IgnoreInvalidPlayerName = true

[Signature]
LoginWithSecureProfile = true
SignChat = true
SignMessageInCommand = true
MarkLegallySignedMsg = true
MarkModifiedMsg = true
MarkIllegallySignedMsg = true
MarkSystemMessage = true
ShowModifiedChat = true
ShowIllegalSignedChat = true

[Logging]
DebugMessages = false
ChatMessages = true
InfoMessages = true
WarningMessages = true
ErrorMessages = true
ChatFilterRegex = ".*"
DebugFilterRegex = ".*"
FilterMode = "disable"
LogToFile = {{LogToFile}}
LogFile = "console-log.txt"
PrependTimestamp = {{PrependTimestamp}}
SaveColorCodes = false

[Console]
[Console.General]
ConsoleMode = "classic"
ConsoleColorMode = "vt100_24bit"
Display_Icon_Banner = true
Display_Input = true
History_Input_Records = 32
TUI_Log_Scrollback = 0

[ChatBot.AutoRelog]
Enabled = false
Delay = { min = 3.0, max = 3.0 }
Retries = 3
Ignore_Kick_Message = false
Kick_Messages = [ "Connection has been lost", "Server is restarting", "Server is full", "Too Many people" ]
